"""Add session time tracking columns

Revision ID: 57ac40682023
Revises: 67ad237ff8fb
Create Date: 2025-09-29 17:07:57.783295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ac40682023'
down_revision: Union[str, None] = '67ad237ff8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time_seconds', sa.Integer(), default=0, nullable=True))
        batch_op.add_column(sa.Column('max_duration_minutes', sa.Integer(), default=45, nullable=True))

    # Update existing rows to set defaults
    op.execute("UPDATE sessions SET total_time_seconds = 0 WHERE total_time_seconds IS NULL")
    op.execute("UPDATE sessions SET max_duration_minutes = 45 WHERE max_duration_minutes IS NULL")

    # Calculate total_time_seconds for existing completed sessions
    op.execute("""
        UPDATE sessions
        SET total_time_seconds = CAST(
            (julianday(completed_at) - julianday(started_at)) * 24 * 60 * 60 AS INTEGER
        )
        WHERE completed_at IS NOT NULL AND started_at IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('max_duration_minutes')
        batch_op.drop_column('total_time_seconds')
    # ### end Alembic commands ###
